#!/usr/bin/env bash

set -euo pipefail

if [[ "${USER}" != "griwes" && "${USER}" != "mdominiak" && "${GRIWES_DOTFILES_DISREGARD_USERNAME:-0}" -ne 1 ]]
then
    echo "You are (probably) not griwes."
    echo "Please take some time reading through this script to avoid surprises."
    echo "Also remember to, at the very least, change the git config..."
    exit 1
fi

dot_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"

set -x

echo Downloading mise and installing tools...
curl -fsSL https://mise.run | zsh

mkdir -p "${HOME}/.config" "${HOME}/.ssh/cm_sockets"
ln -sfn "${dot_dir}/mise" "${HOME}/.config/mise"
"${HOME}/.local/bin/mise" install

simple_configs=(
    atuin
    dunst
    i3
    kitty
    mise
    neovide
    nvim
    polybar
    rofi
    systemd
)

declare -A special_configs=(
    [git/config]="${HOME}/.gitconfig"
    [ssh/config]="${HOME}/.ssh/config"
    [starship/starship.toml]="${HOME}/.config/starship.toml"
    [topgrade/topgrade.toml]="${HOME}/.config/topgrade.toml"
    [zsh/zimrc]="${HOME}/.zimrc"
    [zsh/zshrc]="${HOME}/.zshrc"
)

for config in "${simple_configs[@]}"
do
    ln -sfn "${dot_dir}/${config}" "${HOME}/.config/${config}"
done

for key in "${!special_configs[@]}"
do
    ln -sfn "${dot_dir}/${key}" "${special_configs[${key}]}"
done

zsh_path="$(command -v zsh)"
current_shell="$(getent passwd "${USER}" | awk -F':' '{ print $7 }')"
if [[ "${current_shell}" != "${zsh_path}" ]]
then
    chsh -s "${zsh_path}"
fi

echo Setup complete.
