#!/usr/bin/env bash

set -e

if [[ "${USER}" != "griwes" && "${USER}" != "mdominiak" && "${GRIWES_DOTFILES_DISREGARD_USERNAME}" -ne 1 ]]
then
    echo "You are (probably) not griwes."
    echo "Please take some time reading through this script to avoid surprises."
    echo "Also remember to, at the very least, change the git config..."
    exit 1
fi

do_which() {
    if ! which $1 >/dev/null
    then
        echo "$1 not installed! Make sure you have: nvim, pip3, git, tmux, zsh."
        exit 1
    fi
}

do_which nvim
do_which pip3
do_which git
do_which tmux
do_which zsh

dot_dir=$(dirname $(readlink -f $BASH_SOURCE[0]))

set -x

echo Configuring git...
ln -sfn "${dot_dir}/git/config" ~/.gitconfig

echo Configuring i3...
ln -sfn "${dot_dir}/i3" ~/.config/i3

pip3 install --user i3-workspace-groups

echo Configuring polybar...
ln -sfn "${dot_dir}/polybar" ~/.config/polybar

echo Configuring nvim...
ln -sfn "${dot_dir}/nvim" ~/.config/nvim

pip3 install --user pynvim python-language-server
nvim +PlugInstall +qall
nvim +UpdateRemotePlugins +qall

echo Configuring ssh...
ln -sfn "${dot_dir}/ssh/config" ~/.ssh/config
mkdir -p ~/.ssh/cm_sockets

echo Configuring alacritty...
ln -sfn "${dot_dir}/alacritty" ~/.config/alacritty

echo Configuring tmux...
ln -sfn "${dot_dir}/tmux/tmux.conf" ~/.tmux.conf
ln -sfn "${dot_dir}/tmux" ~/.tmux
cd "${dot_dir}/tmux"
make tmux.conf
cd - >/dev/null

echo Configuring zsh...
ln -sfn "${dot_dir}/zsh/zshrc" ~/.zshrc
ln -sfn "${dot_dir}/zsh/p10k.zsh" ~/.p10k.zsh
if [ "$(finger "${USER}" | grep -oP 'Shell: \K.*')" != "$(which zsh)" ]
then
    chsh -s $(which zsh)
fi

echo Installing fzf...
if [ ! -d ~/.fzf ]
then
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
    ~/.fzf/install
fi

echo Setup complete.

