#!/usr/bin/env bash

set -e

for dir in /sys/bus/platform/drivers/ac/*
do
    if [ ! -L "${dir}" ] || [ "$(basename "${dir}")" == "module" ]
    then
        continue
    fi

    for ac in "${dir}"/power_supply/*
    do
        ac_name=$(basename "${ac}")
        is_online=$(cat "${ac}/online")

        printf "%s:%d\n" "${ac_name}" "${is_online}"
    done
done

