[tools]
bat = "latest"
bottom = "latest"
cargo-binstall = "latest"
cmake = "latest"
dive = "latest"
dust = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
hyperfine = "latest"
jq = "latest"
lsd = "latest"
ninja = "latest"
pre-commit = "latest"
ripgrep = "latest"
sqlite = "latest"
starship = "latest"
usage = "latest"
uv = "latest"
yq = "latest"
yt-dlp = "latest"
zoxide = "latest"
