[tools]
bat = "latest"
"cargo:atuin" = "latest"
"cargo:mcat" = "latest"
"cargo:spacer" = "latest"
"cargo:xcp" = "latest"
dust = "latest"
fd = "latest"
fzf = "latest"
jq = "latest"
lsd = "latest"
ripgrep = "latest"
starship = "latest"
"pipx:thefuck" = "latest"
usage = "latest"
yq = "latest"
zoxide = "latest"
