[tools]
"asdf:sccache" = "latest"
"cargo:atuin" = "latest"
"cargo:bluetui" = "latest"
"cargo:bob-nvim" = "latest"
"cargo:cargo-seek" = "latest"
"cargo:cargo-update" = "latest"
"cargo:csvlens" = "latest"
"cargo:cyme" = "latest"
"cargo:git-delta" = "latest"
"cargo:gping" = "latest"
"cargo:jolt-tui" = "latest"
"cargo:lemmeknow" = "latest"
"cargo:mcat" = "latest"
"cargo:procs" = "latest"
"cargo:purple-ssh" = "latest"
"cargo:rustormy" = "latest"
"cargo:spacer" = "latest"
"cargo:stylua" = "latest"
"cargo:systemd-manager-tui" = "latest"
"cargo:systeroid" = "latest"
"cargo:systeroid-tui" = "latest"
"cargo:tokei" = "latest"
"cargo:topgrade" = "latest"
"cargo:trippy" = "latest"
"cargo:tzupdate" = "latest"
"cargo:wiremix" = "latest"
"cargo:wrkflw" = "latest"
"cargo:xcp" = "latest"
