[tools]
"asdf:sccache" = "latest"
"cargo:bob-nvim" = "latest"
"cargo:cargo-seek" = "latest"
"cargo:cargo-update" = "latest"
"cargo:stylua" = "latest"
"cargo:tokei" = "latest"
cmake = "latest"
hyperfine = "latest"
ninja = "latest"
"npm:@devcontainers/cli" = "latest"
"pipx:flameshow" = "latest"
"pipx:lit" = "latest"
"pipx:py-spy" = "latest"
pre-commit = "latest"
sqlite = "latest"
