[tools]
"go:github.com/isaacphi/mcp-language-server" = "latest"
"go:github.com/stefanlogue/meteor" = "latest"
"go:go.kenn.io/roborev/cmd/roborev" = "latest"
"npm:@devcontainers/cli" = "latest"
"npm:@github/copilot" = "latest"
"npm:@upstash/context7-mcp" = "latest"
"npm:@zed-industries/codex-acp" = "latest"
"npm:oh-my-codex" = "0.18.8"
"pipx:flameshow" = "latest"
"pipx:i3-workspace-groups" = "latest"
"pipx:keeprofi" = "latest"
"pipx:lit" = "latest"
"pipx:llmfit" = "latest"
"pipx:numpy" = "latest"
"pipx:py-spy" = "latest"
"pipx:pywal" = "latest"
"pipx:speedtest-cli" = "latest"
"pipx:sshclick" = "latest"
"pipx:thefuck" = "latest"
"pipx:tiptop" = "latest"
