[tools]
bottom = "latest"
"cargo:bluetui" = "latest"
"cargo:cyme" = "latest"
"cargo:gping" = "latest"
"cargo:jolt-tui" = "latest"
"cargo:lemmeknow" = "latest"
"cargo:procs" = "latest"
"cargo:purple-ssh" = "latest"
"cargo:rustormy" = "latest"
"cargo:systemd-manager-tui" = "latest"
"cargo:systeroid" = "latest"
"cargo:systeroid-tui" = "latest"
"cargo:trippy" = "latest"
"cargo:tzupdate" = "latest"
"cargo:wiremix" = "latest"
dive = "latest"
"github:devnullvoid/pvetui" = "latest"
"github:Harry-kp/vortix" = "latest"
"github:ramonvermeulen/whosthere" = "latest"
"github:shazow/wifitui" = "latest"
"pipx:speedtest-cli" = "latest"
"pipx:sshclick" = "latest"
"pipx:tiptop" = "latest"
tuned-switcher = "1.1.1"
