return {
    {
        'esmuellert/codediff.nvim',
        cmd = {
            'CodeDiff',
        },
        opts = {
            diff = {
                conflict_result_position = 'center',
            },
            explorer = {
                view_mode = 'tree',
                flatten_dirs = true,
                focus_on_select = true,
            },
            keymaps = {
                view = {
                    quit = 'q',
                    toggle_explorer = 'hct',
                    focus_explorer = 'hce',
                    next_hunk = ']h',
                    prev_hunk = '[h',
                    next_file = ']f',
                    prev_file = '[f',
                    diff_get = 'do',
                    diff_put = 'dp',
                    open_in_prev_tab = 'gf',
                    close_on_open_in_prev_tab = false,
                    toggle_stage = '-',
                    stage_hunk = 'hgs',
                    unstage_hunk = 'hgU',
                    discard_hunk = 'hgu',
                    hunk_textobject = 'ih',
                    show_help = 'g?',
                    align_move = 'hgm',
                    toggle_layout = 'hgd',
                },
                explorer = {
                    select = '<CR>',
                    hover = 'K',
                    refresh = 'R',
                    toggle_view_mode = 'hcv',
                    stage_all = 'hgS',
                    unstage_all = 'hgU',
                    restore = 'hgR',
                    toggle_changes = 'hcu',
                    toggle_staged = 'hcs',
                    fold_open = 'zo',
                    fold_open_recursive = 'zO',
                    fold_close = 'zc',
                    fold_close_recursive = 'zC',
                    fold_toggle = 'za',
                    fold_toggle_recursive = 'zA',
                    fold_open_all = 'zR',
                    fold_close_all = 'zM',
                },
                history = {
                    select = '<CR>',
                    toggle_view_mode = 'hcv',
                    refresh = 'R',
                    fold_open = 'zo',
                    fold_open_recursive = 'zO',
                    fold_close = 'zc',
                    fold_close_recursive = 'zC',
                    fold_toggle = 'za',
                    fold_toggle_recursive = 'zA',
                    fold_open_all = 'zR',
                    fold_close_all = 'zM',
                },
                conflict = {
                    accept_incoming = 'hci',
                    accept_current = 'hcc',
                    accept_both = 'hcb',
                    discard = 'hcx',
                    accept_all_incoming = 'hCi',
                    accept_all_current = 'hCc',
                    accept_all_both = 'hCb',
                    discard_all = 'hCx',
                    next_conflict = ']x',
                    prev_conflict = '[x',
                    diffget_incoming = '2do',
                    diffget_current = '3do',
                },
            },
        },
        keys = {
            { 'hcd', '<cmd>CodeDiff<cr>', desc = '󰕚 Open CodeDiff' },
        },
    },
}
