ZVM_INIT_MODE=sourcing
ZVM_LINE_INIT_MODE=$ZVM_MODE_INSERT
ZVM_VI_INSERT_ESCAPE_BINDKEY=jk

POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true

export ADOTDIR=~/.local/share/zsh/antigen

if [ ! -f "${ADOTDIR}/antigen.zsh" ]
then
    echo "Downloading antigen..."
    mkdir -p "${ADOTDIR}"
    curl -L git.io/antigen > "${ADOTDIR}/antigen.zsh" >/dev/null
fi
source "${ADOTDIR}/antigen.zsh"

antigen use oh-my-zsh
antigen theme romkatv/powerlevel10k

antigen bundle debian
antigen bundle docker
antigen bundle extract
antigen bundle fbterm
antigen bundle git
antigen bundle gpg-agent
antigen bundle pip
antigen bundle ssh-agent
antigen bundle svn-fast-info
antigen bundle tig

antigen bundle jeffreytse/zsh-vi-mode

antigen bundle per-directory-history

antigen bundle Aloxaf/fzf-tab

antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-completions

antigen bundle popstas/zsh-command-time
antigen bundle MichaelAquilina/zsh-you-should-use

antigen bundle supercrabtree/k

antigen bundle z-shell/F-Sy-H --branch=main
antigen bundle hchbaw/zce.zsh
# last bundle!
antigen bundle zsh-users/zsh-history-substring-search

antigen apply

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
source ~/.p10k.zsh

HISTFILE=~/.zsh_history
HISTSIZE=999999999
SAVEHIST=999999999
setopt INC_APPEND_HISTORY_TIME

# zsh-history-substring-search configuration
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down
HISTORY_SUBSTRING_SEARCH_ENSURE_UNIQUE=1

bindkey -s "^L" 'clear && tmux clear-history\n'

zvm_bindkey vicmd ',f' zce

# remind about things... after
export YSU_MESSAGE_POSITION="after"

# welcome to glorious new future
EDITOR=nvim
alias vim=nvim

# and to the less glorious too
alias tmux='systemd-run --scope --user --quiet tmux'

# though there's still some glory even with systemd-run
alias iceccmake='CCACHE_PREFIX=icecc systemd-run --scope --user -p MemoryLimit=100G nice -n 10 make -j'

# when in tmux, ring a bell every time a command finishes
precmd() {
    if [ -n ${TMUX+x} ]
    then
        echo -n -e "\a"
    fi
}

# override `ssh` to invoke magic necessary by the tmux status line
# NOTE: that will only work on posix targets. use \ssh to connect to, say, windows
ssh() {
    ~/.tmux/scripts/fauxssh $@
}

# same, but for eternal terminal
et() {
    ~/.tmux/scripts/fauxet $@
}

export EDITOR='nvim'
export PATH="$HOME/.local/bin:$PATH"
