ZIM_HOME=~/.local/share/zim

has() {
  command -v "$1" >/dev/null 2>&1
}

if [[ ! -e ${ZIM_HOME}/zimfw.zsh ]]; then
  if has curl; then
    curl -fsSL --create-dirs -o ${ZIM_HOME}/zimfw.zsh \
        https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh
  else
    print -ru2 'zimfw.zsh is missing and curl is unavailable; skipping Zim bootstrap.'
  fi
fi

if [[ -r ${ZIM_HOME}/zimfw.zsh && ! ${ZIM_HOME}/init.zsh -nt ${ZDOTDIR:-${HOME}}/.zimrc ]]; then
  source ${ZIM_HOME}/zimfw.zsh init -q
fi

export PATH="$HOME/.local/bin:$HOME/.local/share/mise/shims:$PATH"
export YSU_MESSAGE_POSITION="after"
export YSU_MODE=ALL

if [[ -r ${ZIM_HOME}/init.zsh ]]; then
  source ${ZIM_HOME}/init.zsh
fi

if [[ -r ~/.ssh/creds ]]; then
  source ~/.ssh/creds
fi

zstyle ':completion:*' format '[%d]'

FZF_GROUP_COLORS=(
    $'\033[34m'
    $'\033[32m'
    $'\033[33m'
    $'\033[35m'
    $'\033[31m'
    $'\033[94m'
    $'\033[92m'
    $'\033[93m'
    $'\033[95m'
    $'\033[91m'
)
zstyle ':fzf-tab:*' group-colors $FZF_GROUP_COLORS

if has lsd; then
  alias ls='lsd --group-directories-first'
  alias ll='lsd -l --group-directories-first'
  alias la='lsd -la --group-directories-first'
  alias tree='lsd -l --group-directories-first --tree --depth=2'
fi

if has zoxide; then
  alias cd='z'
fi

typeset -g -A key

key[Home]="${terminfo[khome]}"
key[End]="${terminfo[kend]}"
key[Insert]="${terminfo[kich1]}"
key[Backspace]="${terminfo[kbs]}"
key[Delete]="${terminfo[kdch1]}"
key[Up]="${terminfo[kcuu1]}"
key[Down]="${terminfo[kcud1]}"
key[Left]="${terminfo[kcub1]}"
key[Right]="${terminfo[kcuf1]}"
key[PageUp]="${terminfo[kpp]}"
key[PageDown]="${terminfo[knp]}"
key[Shift-Tab]="${terminfo[kcbt]}"
key[Control-Left]="${terminfo[kLFT5]}"
key[Control-Right]="${terminfo[kRIT5]}"

[[ -n "${key[Home]}"          ]] && bindkey -- "${key[Home]}"          beginning-of-line
[[ -n "${key[End]}"           ]] && bindkey -- "${key[End]}"           end-of-line
[[ -n "${key[Insert]}"        ]] && bindkey -- "${key[Insert]}"        overwrite-mode
[[ -n "${key[Backspace]}"     ]] && bindkey -- "${key[Backspace]}"     backward-delete-char
[[ -n "${key[Delete]}"        ]] && bindkey -- "${key[Delete]}"        delete-char
[[ -n "${key[Left]}"          ]] && bindkey -- "${key[Left]}"          backward-char
[[ -n "${key[Right]}"         ]] && bindkey -- "${key[Right]}"         forward-char
[[ -n "${key[Control-Left]}"  ]] && bindkey -- "${key[Control-Left]}"  backward-word
[[ -n "${key[Control-Right]}" ]] && bindkey -- "${key[Control-Right]}" forward-word

# Finally, make sure the terminal is in application mode, when zle is
# active. Only then are the values from $terminfo valid.
if (( ${+terminfo[smkx]} && ${+terminfo[rmkx]} )); then
	autoload -Uz add-zle-hook-widget
	function zle_application_mode_start { echoti smkx }
	function zle_application_mode_stop { echoti rmkx }
	add-zle-hook-widget -Uz zle-line-init zle_application_mode_start
	add-zle-hook-widget -Uz zle-line-finish zle_application_mode_stop
fi
