#!/usr/bin/env bash

window_width=$(tmux display-message -p '#{window_width}')
if [[ "${window_width}" -lt 150 ]]
then
    date +"%X"
elif [[ "${window_width}" -lt 250 ]]
then
    date +"%x %X"
else
    date
fi

