# exit if noninteractive
if [ -z "$PS1" ]
then
    return
fi

bashrc_dir=$(dirname $(readlink -f "$BASH_SOURCE"))

export BASH_RC_PATH=$bashrc_dir/rc
export BASH_COMPLETION_DIR=$bashrc_dir/completion

export DOTFILES_PATH=$(readlink -f $bashrc_dir/..)

for file in $BASH_RC_PATH/*.sh
do
    source "$file"
done

